version: '3.3'
services:
  soap-service:
    container_name: soap_service
    build: 
      dockerfile: Dockerfile
    ports: 
      - 8081:8081
    environment:
      - mysql://db/saranghaengbok_soap